# Generated by Django 5.1.6 on 2025-02-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("CoinMarketCap", "CoinMarketCap"),
                            ("Blockchair", "Blockchair"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("api_key", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
                "db_table": "provider",
            },
        ),
    ]
